---
kind: pipeline
name: user-debian-7-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 7-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:7-slim

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 7-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:7-slim

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 7-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:7

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 7-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:7

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 7
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-8-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 8-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8-slim

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 8-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8-slim

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 8-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-8
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 8-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 8-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 8
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-9-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9-slim

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9-slim

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-slim-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9-slim

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 9-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-9
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: 9-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 9
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:latest

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:latest

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    tags: latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:latest

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

