---
kind: pipeline
name: prepare
trigger:
  branch:
  - master
  event:
  - push
clone:
  disable: true

steps:
- name: register-qemu
  image: multiarch/qemu-user-static:register
  command: [ "--reset" ]
  privileged: true

---
kind: pipeline
name: user-debian-7-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 7-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:7-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 7-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:7-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 7-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:7
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 7-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:7
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 7
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-8-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 8-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 8-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 8-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-8
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 8-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 8-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 8
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-9-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-slim-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9-slim
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 9-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-9
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: 9-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 9
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-debian-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian amd64 arm32v7 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:latest
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:latest
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-debian
    create_repository: true
    use_cache: true
    tags: latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:latest
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

