---
kind: pipeline
name: user-debian-10-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm64v8 arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-slim-arm64v8
    repo: phasecorex/user-debian
    tags:
      - buster-slim-arm64v8
      - 10-slim-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:10-slim
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-slim-arm32v7
    repo: phasecorex/user-debian
    tags:
      - buster-slim-arm32v7
      - 10-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:10-slim
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-slim-arm32v5
    repo: phasecorex/user-debian
    tags:
      - buster-slim-arm32v5
      - 10-slim-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:10-slim
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-slim-amd64
    repo: phasecorex/user-debian
    tags:
      - buster-slim-amd64
      - 10-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:10-slim
      - ARCH=amd64

- name: docker-push-manifest-buster-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: buster-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-10-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: 10-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-8-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-slim-arm32v7
    repo: phasecorex/user-debian
    tags:
      - jessie-slim-arm32v7
      - 8-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8-slim
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-slim-arm32v5
    repo: phasecorex/user-debian
    tags:
      - jessie-slim-arm32v5
      - 8-slim-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:8-slim
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-slim-amd64
    repo: phasecorex/user-debian
    tags:
      - jessie-slim-amd64
      - 8-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8-slim
      - ARCH=amd64

- name: docker-push-manifest-jessie-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: jessie-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-8-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: 8-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-8
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-arm32v7
    repo: phasecorex/user-debian
    tags:
      - jessie-arm32v7
      - 8-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:8
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-arm32v5
    repo: phasecorex/user-debian
    tags:
      - jessie-arm32v5
      - 8-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:8
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:8-amd64
    repo: phasecorex/user-debian
    tags:
      - jessie-amd64
      - 8-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:8
      - ARCH=amd64

- name: docker-push-manifest-jessie
  image: plugins/manifest
  environment:
    DRONE_TAG: jessie
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-8
  image: plugins/manifest
  environment:
    DRONE_TAG: 8
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-9-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm64v8 arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-slim-arm64v8
    repo: phasecorex/user-debian
    tags:
      - stretch-slim-arm64v8
      - 9-slim-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9-slim
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-slim-arm32v7
    repo: phasecorex/user-debian
    tags:
      - stretch-slim-arm32v7
      - 9-slim-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9-slim
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-slim-arm32v5
    repo: phasecorex/user-debian
    tags:
      - stretch-slim-arm32v5
      - 9-slim-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:9-slim
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-slim-amd64
    repo: phasecorex/user-debian
    tags:
      - stretch-slim-amd64
      - 9-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9-slim
      - ARCH=amd64

- name: docker-push-manifest-stretch-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: stretch-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-9-slim
  image: plugins/manifest
  environment:
    DRONE_TAG: 9-slim
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-9
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm64v8 arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-arm64v8
    repo: phasecorex/user-debian
    tags:
      - stretch-arm64v8
      - 9-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:9
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-arm32v7
    repo: phasecorex/user-debian
    tags:
      - stretch-arm32v7
      - 9-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:9
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-arm32v5
    repo: phasecorex/user-debian
    tags:
      - stretch-arm32v5
      - 9-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:9
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:9-amd64
    repo: phasecorex/user-debian
    tags:
      - stretch-amd64
      - 9-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:9
      - ARCH=amd64

- name: docker-push-manifest-stretch
  image: plugins/manifest
  environment:
    DRONE_TAG: stretch
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-9
  image: plugins/manifest
  environment:
    DRONE_TAG: 9
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-debian-10
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-debian arm64v8 arm32v7 arm32v5 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-arm64v8
    repo: phasecorex/user-debian
    tags:
      - buster-arm64v8
      - 10-arm64v8
      - latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/debian:10
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-arm32v7
    repo: phasecorex/user-debian
    tags:
      - buster-arm32v7
      - 10-arm32v7
      - latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/debian:10
      - ARCH=arm32v7

- name: docker-build-arm32v5
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-arm32v5
    repo: phasecorex/user-debian
    tags:
      - buster-arm32v5
      - 10-arm32v5
      - latest-arm32v5
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v5/debian:10
      - ARCH=arm32v5

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-debian:10-amd64
    repo: phasecorex/user-debian
    tags:
      - buster-amd64
      - 10-amd64
      - latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/debian:10
      - ARCH=amd64

- name: docker-push-manifest-buster
  image: plugins/manifest
  environment:
    DRONE_TAG: buster
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-10
  image: plugins/manifest
  environment:
    DRONE_TAG: 10
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-latest
  image: plugins/manifest
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - user-debian-10-slim
  - user-debian-8-slim
  - user-debian-8
  - user-debian-9-slim
  - user-debian-9
  - user-debian-10

